### ISSUE TITLE
Checklist to completion

### ISSUE THREAD

**Issue by rsweetland** [internet-simplicity/buttons-work#1]
- [x] Make example "just work" with button and screen record it.
- [x] Verify pin #19 is pull down or neutral
- [x] Make final how-to vid showing button "just working"
- [ ] Put content on template, reach out to Howdy.ai / Slack / Hackster.io / HackADay
